Grossum\MenuBundle\Entity\BaseMenu:
    type: mappedSuperclass
    table: menu
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
