Grossum\MenuBundle\Entity\BaseMenuItem:
    type: mappedSuperclass
    table: menu_item
    fields:
        title:
            type: string
            length: 255
        url:
            type: string
            length: 255
        entityClass:
            type: string
            length: 255
            column: entity_class
        entityIdentifier:
            type: string
            length: 255
            column: entity_identifier
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
