services:
    grossum_menu.admin.menu:
        class: %grossum_menu.menu.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "grossum_menu.admin.menu.label" }
        arguments:
            - ~
            - %grossum_menu.menu.entity.class%
            - ~
