services:
    grossum_menu.admin.menu:
        class: %grossum_menu.menu.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "grossum_menu.admin.menu.label" }
        arguments:
            - ~
            - %grossum_menu.menu.entity.class%
            - ~
        calls:
            - [addChild, ["@grossum_menu.admin.menu_item"]]

    grossum_menu.admin.menu_item:
        class: %grossum_menu.menu_item.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm,  show_in_dashboard: false, label: "grossum_menu.admin.menu_item.label" }
        arguments:
            - ~
            - %grossum_menu.menu_item.entity.class%
            - GrossumMenuBundle:MenuItemAdmin
        calls:
            - [setMenuItemManager, ["@grossum_menu.entity.manager.menu_item.manager"]]
            - [setMenuMaster, ["@grossum_menu.menu.manager"]]
            - [setTemplates, [{list: "GrossumMenuBundle:MenuItemAdmin:list.html.twig", edit: "GrossumMenuBundle:MenuItemAdmin:edit.html.twig"}]]

    grossum_menu.admin.menu_extension:
        class: %grossum_menu.admin.menu_extension.class%
        arguments:
            - @grossum_menu.entity.manager.menu_item.manager
        tags:
            - { name: sonata.admin.extension, target: grossum_menu.admin.menu }

    grossum_menu.admin.menu_item_extension:
        class: %grossum_menu.admin.menu_item_extension.class%
        arguments:
            - @grossum_menu.entity.manager.menu_item.manager
        tags:
            - { name: sonata.admin.extension, target: grossum_menu.admin.menu_item }
