parameters:
    grossum_menu.menu.admin.class: Grossum\MenuBundle\Admin\MenuAdmin
    grossum_menu.menu.entity.class: Grossum\MenuBundle\Entity\BaseMenu
    grossum_menu.menu.manager.class: Grossum\MenuBundle\Entity\EntityManager\BaseMenuManager
