parameters:
    grossum_menu_tree_depth: 32

services:
    grossum_menu.entity_manager.menu.manager:
        class: %grossum_menu.entity_manager.menu.class%
        arguments:
            - @grossum_core.entity_manager
            - %grossum_menu.menu.entity.class%

    grossum_menu.entity.manager.menu_item.manager:
        class: %grossum_menu.entity_manager.menu_item.class%
        arguments:
            - @grossum_core.entity_manager
            - %grossum_menu.menu_item.entity.class%

    grossum_menu.menu.manager:
        class: %grossum_menu.menu.manager.class%

    grossum_menu.abstract.menu_handler:
        class: %grossum_menu.abstract.menu_handler.class%
        abstract: true
        arguments:
            - @router

    grossum_menu.form.type.menu_entity_class:
        class: %grossum_menu.form.type.menu_entity_class.class%
        arguments:
            - @grossum_menu.menu.manager
        tags:
            - { name: form.type, alias: 'grossum_menu_entity_class'}

    grossum_menu.form.type.menu_entity_identifier:
        class: %grossum_menu.form.type.menu_entity_identifier.class%
        arguments:
            - @grossum_menu.menu.manager
        tags:
            - { name: form.type, alias: 'grossum_menu_entity_identifier'}

    grossum_menu.event_listener.menu_subscriber:
        class: Grossum\MenuBundle\EventListener\MenuSubscriber
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    grossum_menu.event_listener.menu_item_subscriber:
        class: Grossum\MenuBundle\EventListener\MenuItemSubscriber
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber, connection: default }
